#!/usr/bin/env sh
# Bring up (or tear down) the local checkout smoke-test environment:
# scaffolds .env.test-profile.local from 1Password's .env, starts stripe listen,
# captures the webhook secret, and starts the dev server with the test overlay.
#
# Usage:
#   scripts/checkout-smoke.sh up       # bring everything up; idempotent
#   scripts/checkout-smoke.sh down     # tear everything down
#   scripts/checkout-smoke.sh status   # show what's running

set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT_DIR"

STRIPE_PID_FILE="/tmp/tumwater-stripe-listen.pid"
STRIPE_LOG="/tmp/tumwater-stripe-listen.log"
DEV_PID_FILE="/tmp/tumwater-dev.pid"
DEV_LOG="/tmp/tumwater-dev.log"
DEV_PORT="${DEV_PORT-3000}"

cmd="${1-up}"

kill_pidfile() {
  pf="$1"
  [ -f "$pf" ] || return 0
  pid="$(cat "$pf" 2>/dev/null || true)"
  [ -n "$pid" ] && kill "$pid" 2>/dev/null || true
  rm -f "$pf"
}

cmd_down() {
  kill_pidfile "$STRIPE_PID_FILE"
  pkill -f "stripe listen.*api/webhooks/stripe" 2>/dev/null || true

  kill_pidfile "$DEV_PID_FILE"
  port_pid="$(lsof -ti tcp:"$DEV_PORT" 2>/dev/null || true)"
  [ -n "$port_pid" ] && kill $port_pid 2>/dev/null || true

  printf '%s\n' "checkout smoke env stopped."
}

cmd_status() {
  if [ -f "$STRIPE_PID_FILE" ] && kill -0 "$(cat "$STRIPE_PID_FILE")" 2>/dev/null; then
    printf 'stripe listen: running (pid %s, log %s)\n' "$(cat "$STRIPE_PID_FILE")" "$STRIPE_LOG"
  else
    printf 'stripe listen: stopped\n'
  fi
  port_pid="$(lsof -ti tcp:"$DEV_PORT" 2>/dev/null || true)"
  if [ -n "$port_pid" ]; then
    printf 'dev server: running on :%s (pid %s, log %s)\n' "$DEV_PORT" "$port_pid" "$DEV_LOG"
  else
    printf 'dev server: stopped\n'
  fi
}

require_var() {
  var_name="$1"
  eval "var_value=\${$var_name-}"
  if [ -z "$var_value" ]; then
    printf '%s\n' "Missing $var_name after sourcing .env." >&2
    printf '%s\n' "  The 1Password local-env-file is a named pipe; 1Password may need your approval before it serves content." >&2
    printf '%s\n' "  Click the 1Password notification (or open the linked item) and re-run this command." >&2
    exit 1
  fi
}

cmd_up() {
  command -v stripe >/dev/null 2>&1 || {
    printf '%s\n' "stripe CLI not found. Install: brew install stripe/stripe-cli/stripe" >&2
    exit 1
  }
  # .env is typically a 1Password-managed named pipe, so use -e (any file type), not -f.
  [ -e .env ] || {
    printf '%s\n' ".env missing — open 1Password desktop and link the env item, or generate one manually." >&2
    exit 1
  }

  # Load the 1Password-generated .env so we can read *_TEST_* values.
  set -a
  # shellcheck disable=SC1091
  . ./.env
  set +a

  require_var STRIPE_TEST_SECRET_KEY
  require_var NEXT_PUBLIC_STRIPE_TEST_PUBLISHABLE_KEY
  require_var RESEND_TEST_API_KEY
  require_var HOST_TEST_EMAIL
  require_var PRICELABS_API_KEY
  require_var STUDIO_ICAL_URL
  require_var ONEBR_ICAL_URL

  # Tear down any prior run so this is idempotent.
  cmd_down >/dev/null 2>&1 || true

  # Scaffold .env.test-profile.local if missing. If the user has customised it,
  # leave their content alone (we only refresh STRIPE_WEBHOOK_SECRET below).
  if [ ! -f .env.test-profile.local ]; then
    cat > .env.test-profile.local <<EOF
# Generated by scripts/checkout-smoke.sh from .env on $(date -u +%FT%TZ)
STRIPE_SECRET_KEY=$STRIPE_TEST_SECRET_KEY
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_TEST_PUBLISHABLE_KEY
RESEND_API_KEY=$RESEND_TEST_API_KEY
HOST_EMAIL=$HOST_TEST_EMAIL
PRICELABS_API_KEY=$PRICELABS_API_KEY
STUDIO_ICAL_URL=$STUDIO_ICAL_URL
ONEBR_ICAL_URL=$ONEBR_ICAL_URL
NEXT_PUBLIC_SITE_URL=http://localhost:$DEV_PORT
STRIPE_WEBHOOK_SECRET=whsec_pending
EOF
    printf '%s\n' "Wrote .env.test-profile.local"
  fi

  : > "$STRIPE_LOG"
  stripe listen \
    --api-key "$STRIPE_TEST_SECRET_KEY" \
    --forward-to "http://localhost:$DEV_PORT/api/webhooks/stripe" \
    > "$STRIPE_LOG" 2>&1 &
  printf '%s\n' "$!" > "$STRIPE_PID_FILE"

  whsec=""
  i=0
  while [ $i -lt 20 ]; do
    sleep 1
    whsec="$(grep -o "whsec_[a-zA-Z0-9]*" "$STRIPE_LOG" 2>/dev/null | head -1 || true)"
    [ -n "$whsec" ] && break
    i=$((i + 1))
  done
  if [ -z "$whsec" ]; then
    printf '%s\n' "stripe listen did not emit a webhook secret. Log:" >&2
    cat "$STRIPE_LOG" >&2
    cmd_down >/dev/null 2>&1 || true
    exit 1
  fi

  # Refresh STRIPE_WEBHOOK_SECRET in the env file with the new whsec.
  awk -v whsec="$whsec" '
    /^STRIPE_WEBHOOK_SECRET=/ { print "STRIPE_WEBHOOK_SECRET=" whsec; next }
    { print }
  ' .env.test-profile.local > .env.test-profile.local.tmp
  mv .env.test-profile.local.tmp .env.test-profile.local

  : > "$DEV_LOG"
  ./scripts/dev-test-profile.sh > "$DEV_LOG" 2>&1 &
  printf '%s\n' "$!" > "$DEV_PID_FILE"

  i=0
  while [ $i -lt 30 ]; do
    if curl -sf -o /dev/null "http://localhost:$DEV_PORT" 2>/dev/null; then
      printf '%s\n' "checkout smoke env ready"
      printf '  dev:     http://localhost:%s (log: %s)\n' "$DEV_PORT" "$DEV_LOG"
      printf '  stripe:  forwarding to /api/webhooks/stripe (log: %s)\n' "$STRIPE_LOG"
      printf '  whsec:   %s\n' "$whsec"
      printf '%s\n' "stop with: scripts/checkout-smoke.sh down"
      exit 0
    fi
    sleep 1
    i=$((i + 1))
  done

  printf '%s\n' "dev server did not become ready in time. Log:" >&2
  tail -40 "$DEV_LOG" >&2
  cmd_down >/dev/null 2>&1 || true
  exit 1
}

case "$cmd" in
  up) cmd_up ;;
  down) cmd_down ;;
  status) cmd_status ;;
  *)
    printf '%s\n' "Usage: $0 [up|down|status]" >&2
    exit 2
    ;;
esac
